//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {
        public int id { get; set; }
        
        [Required(ErrorMessage = "name必須填寫")]
        [RegularExpression(@"^[\u4e00-\u9fa5a-zA-Z]{2,}$", ErrorMessage = "至少2個中英文字母")]
        public string name { get; set; }

        [Required(ErrorMessage = "username必須填寫")]
        [RegularExpression(@"^\w{4,}$", ErrorMessage = "username至少4個英文與數字，可加底線")]
        public string username { get; set; }

        [Required(ErrorMessage = "password必須填寫")]
        [RegularExpression(@"^\w{6,}$", ErrorMessage = "password至少6個英文與數字，可加底線")]
        public string password { get; set; }

        [Required(ErrorMessage = "registerDate必須填寫")]
        public Nullable<System.DateTime> registerDate { get; set; }
    }
}
